/** Typora / GitHub 常用 :name: 表情映射，供 Lute PutEmojis 与工具栏使用 */
export const TYPORA_EMOJI_MAP: Record<string, string> = {
  '+1': '👍',
  '-1': '👎',
  '100': '💯',
  confused: '😕',
  cry: '😢',
  eyes: '👀',
  heart: '❤️',
  joy: '😂',
  ok_hand: '👌',
  rocket: '🚀',
  smile: '😄',
  tada: '🎉',
  thumbsup: '👍',
  thumbsdown: '👎',
  wink: '😉',
  thinking: '🤔',
  fire: '🔥',
  star: '⭐',
  warning: '⚠️',
  white_check_mark: '✅',
  x: '❌',
  bulb: '💡',
  memo: '📝',
  book: '📖',
  link: '🔗',
  computer: '💻',
  coffee: '☕',
};
